# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-18 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('div', models.CharField(max_length=1)),
                ('branch', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=2)),
            ],
        ),
    ]
